spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    schema: spring3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
        ddl-auto: update
#    если хотите указать свою схему
#    properties:
#      hibernate:
#        default_schema: spring4

jwt:
  security:
    key: hello_world